### ISSUE TITLE
Pro Version

### ISSUE THREAD

**Issue by eduhh94** [Saas-Starter-Kit/SAAS-Starter-Kit-Pro#15]
Hello, where can I purchase the pro version like in the demo?

**Comment by iqbal125** [comment]
I just open sourced the pro version. The pro version is free and is in this repo. 
@eduhh94

**Comment by eduhh94** [comment]
The client is not the pro version.

**Comment by iqbal125** [comment]
umm yes it. What do you mean?

**Comment by SkyYap** [comment]
> 

The pro version already available.
