### ISSUE TITLE
5 depreciated packages including request, har0validator, urix and etc.

### ISSUE THREAD

**Issue by SkyYap** [Saas-Starter-Kit/SAAS-Starter-Kit-Pro#16]
I tried `npm install` and found these:

`npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142`
`npm WARN deprecated har-validator@5.1.5: this library is no longer supported`
`npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated`
`npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated`
`npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142`

I think we should remove these dependencies and change to alternate packages.

**Comment by joeybolohan** [comment]
This would be a great help. Please
