### ISSUE TITLE
JWT token decode failed

### ISSUE THREAD

**Issue by SkyYap** [Saas-Starter-Kit/SAAS-Starter-Kit-Pro#17]
`JWT token decode failed` appeared during login and fail to login.

`src/screens/Auth/helpers.js:128` is having JWT token decode failed. I check back and found out it is because the `src/screens/Auth/helpers.js:122` `token` is not working.

The token in `src/screens/Auth/helpers.js:86` doesn't bring an jwt token. Anyone knows how to solve this?
```
let token = await firebase
    .auth()
    .currentUser.getIdToken()
    .catch((err) => {
      fetchFailure(err);
    }); 
```

**Comment by SkyYap** [comment]
Reopen this as I initiated both client and server part and still this issue is happening.

**Comment by larisonjustin** [comment]
@SkyYap Did you add your AUTH_SECRET in the .env file?

**Comment by SkyYap** [comment]
> @SkyYap Did you add your AUTH_SECRET in the .env file?

Yupp. I have found the issue. I didn't initiate my backend so it doesn't communicate.

**Comment by SkyYap** [comment]
> @SkyYap Did you add your AUTH_SECRET in the .env file?

Yup. I did add AUTH_SECRET.

**Comment by SkyYap** [comment]
Closed as I found no issue running on render.com.
