### ISSUE TITLE
can you provide the video for each addition of software / node so we can help check security of app?

### ISSUE THREAD

**Issue by vipsland** [Saas-Starter-Kit/SAAS-Starter-Kit-Pro#18]
can you provide the video for each addition of software / node so we can help check security of app?

**Comment by iqbal125** [comment]
@vipsland Sorry I dont understand what you mean.

**Comment by SkyYap** [comment]
> can you provide the video for each addition of software / node so we can help check security of app?

Please provide more details and elaboration on your statement please.
