### ISSUE TITLE
Server env contains 'GOOGLE_CLOUD_PROJECT' which the readme.md is not describing 

### ISSUE THREAD

**Issue by SkyYap** [Saas-Starter-Kit/SAAS-Starter-Kit-Pro#19]
In the server -> env.example file, `GOOGLE_CLOUD_PROJECT` is available but not described/indicate the purpose in the homepage readme.md. Do add in the purpose of the `GOOGLE_CLOUD_PROJECT` to ease the user fill up.

**Comment by iqbal125** [comment]
@SkyYap Hey sorry, Ive moved on to other projects and dont have any time to maintain this project anymore. 

If you want to make any changes/updates I would be happy to give you maintainer rights to this repo if you want?

**Comment by SkyYap** [comment]
@iqbal125 Hi! Sure. I am maintaining this repo by having a fork. That will be great if I directly maintain this repo.

**Comment by GreenPowerDev** [comment]
I really like this repo.
Thank you for your contribution.
As a developer, I want to contribute to the improvement of the project.
If you have any problems, please contact me too.

**Comment by SkyYap** [comment]
> I really like this repo. Thank you for your contribution. As a developer, I want to contribute to the improvement of the project. If you have any problems, please contact me too.

Hi GreenPowerDev, feel free to make a pull request to contribute.

**Comment by SkyYap** [comment]
Removed as I didn't find any part in the code is using this.
