### ISSUE TITLE
Are you Still working on this?

### ISSUE THREAD

**Issue by joeybolohan** [Saas-Starter-Kit/SAAS-Starter-Kit-Pro#20]
I wanted to find out if you are still working on this repo?

**Comment by SkyYap** [comment]
> I wanted to find out if you are still working on this repo?

I think only me is working on this repo. I didn't update this repo as I am taking some time to get familiar with this repo but I have cloned this repo and build my own SaaS in a private repo. 

Might consider revive this project if I have time. Feel free to ask any question here and hopefully I can help.

**Comment by joeybolohan** [comment]
Ok cool thanks buddy for the quick response. I saw the last update was a year ago and this is just what I need to get started on a quick project and did not know how out of date some of the packages were and it is was being updated. Thanks for any help!

**Comment by SkyYap** [comment]
> Ok cool thanks buddy for the quick response. I saw the last update was a year ago and this is just what I need to get started on a quick project and did not know how out of date some of the packages were and it is was being updated. Thanks for any help!

I didn't really update those packages. Only fix some parts. But currently the repo contains some of my SaaS logic. I might take 2 weeks to remove out the logic and merge into this repo.

**Comment by iqbal125** [comment]
Yeah hey sorry Ive moved on to other projects and no longer working on this. If you have questions tho I can answer them.

**Comment by SkyYap** [comment]
> Yeah hey sorry Ive moved on to other projects and no longer working on this. If you have questions tho I can answer them.

Hi iqbal, any chance I can get your email and talk to you privately?

**Comment by iqbal125** [comment]
> > Yeah hey sorry Ive moved on to other projects and no longer working on this. If you have questions tho I can answer them.
> 
> Hi iqbal, any chance I can get your email and talk to you privately?

Yeah sure, iqbal125@yahoo

**Comment by joeybolohan** [comment]
It would be super awesome if you would have some time to look over the project and make an package updates to this project.

**Comment by SkyYap** [comment]
> It would be super awesome if you would have some time to look over the project and make an package updates to this project.

Hi, merged, updated and reviving this repo.

**Comment by iqbal125** [comment]
> > It would be super awesome if you would have some time to look over the project and make an package updates to this project.
> 
> Hi, merged, updated and reviving this repo.

Hey man. Thanks for this, but Im actually building a new SAAS boilerplate that will use more modern technologies. Stay tuned.

**Comment by SkyYap** [comment]
> > > It would be super awesome if you would have some time to look over the project and make an package updates to this project.
> > 
> > 
> > Hi, merged, updated and reviving this repo.
> 
> Hey man. Thanks for this, but Im actually building a new SAAS boilerplate that will use more modern technologies. Stay tuned.

I have sent you an email. If the new boilerplate needs any help pm me. I can help if the tech stack is what I want to learn haha.

**Comment by iqbal125** [comment]
> > > > It would be super awesome if you would have some time to look over the project and make an package updates to this project.
> > > 
> > > 
> > > Hi, merged, updated and reviving this repo.
> > 
> > 
> > Hey man. Thanks for this, but Im actually building a new SAAS boilerplate that will use more modern technologies. Stay tuned.
> 
> I have sent you an email. If the new boilerplate needs any help pm me. I can help if the tech stack is what I want to learn haha.

Yeah cool, I replied to your email.

**Comment by luqikhan** [comment]
Hey, guys! I hope you are doing great. I've cloned this repo for my project, but it's not working properly. All the packages and dependencies are not updated. I've worked on it and managed to run this repo, but I'm still having some issues. First, client-side routes are not protected; second, role-based authentication is not working properly. So, I request that you please give some time to fix it. I already appreciate your work. Thanks, guys!

**Comment by SkyYap** [comment]
> Hey, guys! I hope you are doing great. I've cloned this repo for my project, but it's not working properly. All the packages and dependencies are not updated. I've worked on it and managed to run this repo, but I'm still having some issues. First, client-side routes are not protected; second, role-based authentication is not working properly. So, I request that you please give some time to fix it. I already appreciate your work. Thanks, guys!

I am not so sure about the client-side router part protection part. Currently I think the verification of JWT token works properly. Do you mind point out which part of it?

Ya. Role-based restriction using @casl/react is having issue. Do you mind describe the role-based authentication part? I tested and didn't find out. Think I missed out this part.

**Comment by luqikhan** [comment]
> > Hey, guys! I hope you are doing great. I've cloned this repo for my project, but it's not working properly. All the packages and dependencies are not updated. I've worked on it and managed to run this repo, but I'm still having some issues. First, client-side routes are not protected; second, role-based authentication is not working properly. So, I request that you please give some time to fix it. I already appreciate your work. Thanks, guys!
> 
> I am not so sure about the client-side router part protection part. Currently I think the verification of JWT token works properly. Do you mind point out which part of it?
> 
> Ya. Role-based restriction using @casl/react is having issue. Do you mind describe the role-based authentication part? I tested and didn't find out. Think I missed out this part.

Correct Firebase Auth with a Node.js backend is working properly, and the token is saving in local storage. However, when we log out and go to the dashboard by URL, it's not redirecting us to the login page. Another issue is that all users are logging in as admins. There is no way to separate regular users and admins to access specific routes. and one thing more all the packages dep are not updated can you update it..

**Comment by iqbal125** [comment]
> Hey, guys! I hope you are doing great. I've cloned this repo for my project, but it's not working properly. All the packages and dependencies are not updated. I've worked on it and managed to run this repo, but I'm still having some issues. First, client-side routes are not protected; second, role-based authentication is not working properly. So, I request that you please give some time to fix it. I already appreciate your work. Thanks, guys!

Hey man, appreciate you using this repo. 

But Im going to rebuild this boilerplate using modern technologies. The codebase will be much simpler and more robust. Should have it out in the next few weeks, stay tuned.

**Comment by SkyYap** [comment]
> > > Hey, guys! I hope you are doing great. I've cloned this repo for my project, but it's not working properly. All the packages and dependencies are not updated. I've worked on it and managed to run this repo, but I'm still having some issues. First, client-side routes are not protected; second, role-based authentication is not working properly. So, I request that you please give some time to fix it. I already appreciate your work. Thanks, guys!
> > 
> > 
> > I am not so sure about the client-side router part protection part. Currently I think the verification of JWT token works properly. Do you mind point out which part of it?
> > Ya. Role-based restriction using @casl/react is having issue. Do you mind describe the role-based authentication part? I tested and didn't find out. Think I missed out this part.
> 
> Correct Firebase Auth with a Node.js backend is working properly, and the token is saving in local storage. However, when we log out and go to the dashboard by URL, it's not redirecting us to the login page. Another issue is that all users are logging in as admins. There is no way to separate regular users and admins to access specific routes. and one thing more all the packages dep are not updated can you update it..

Ya. There is no protection against the URL. Should block out accessing without login. For the admin part, all users sign up via the website are assigned as admin role and only those who are invited by admin will get a user role. The boilerplate is not separating via specific routes but only through @casl/react. Check it out at Dashboard -> Permissions.

New boilerplate is coming and I don't think I will continue updating it.
